import Link from "next/link";
import { ArrowLeft, ArrowUpRight, Download } from "lucide-react";
export default function Setup() {
  return <main className="setup-page"><Link className="setup-back" href="/"><ArrowLeft size={16} /> Back to Companion</Link><span className="eyebrow warm">MODEL SERVER SETUP</span><h1>Give Gemma a home.</h1><p className="setup-intro">Your companion is configured for Gemma 4 Heretical 31B. It needs its own inference server; the companion website handles the conversation and voice connections.</p>
    <a className="download-button" href="/gemma-model-server.zip" download><Download size={18} /> Download server setup</a>
    <ol className="setup-steps"><li><span>01</span><div><h2>Choose a machine</h2><p>Use Linux with Docker and an NVIDIA GPU, or a Mac running Ollama. The supplied setup defaults to Q4_K_M, about 19 GB of model weights. Allow additional memory for the operating system and conversation context. A 24 GB GPU is a starting point; 32 GB or more gives more room. Actual fit and voice latency must be measured on your hardware.</p></div></li>
    <li><span>02</span><div><h2>Start the model server</h2><p>The download includes a Docker configuration, model installer, authenticated gateway, and a complete README. The installer applies the repository's Gemma 4 renderer and parser fix. It does not retrain or re-abliterate the model.</p><p>For Q8_0, the repository lists about 33 GB for weights alone. Use a host with additional headroom.</p></div></li>
    <li><span>03</span><div><h2>Connect it here</h2><p>Enter the server's HTTPS address and access key in Connections. Add your Deepgram and Cartesia keys, choose a voice, save, then test the connections. Start talking once the checks pass.</p></div></li></ol>
    <div className="setup-note"><h2>What is ready, and what needs you</h2><p>The companion interface and integration code are built. A running Gemma host, Deepgram credentials, and Cartesia credentials are still required. No GPU hosting has been purchased and no model has been loaded in this workspace.</p><p>This community model changes refusal behavior. The repository's refusal and KL-divergence figures do not establish that it is the best conversational model; response quality and latency still need evaluation on your host.</p></div>
    <a className="setup-link" href="https://github.com/pmarreck/gemma4-heretical" target="_blank" rel="noreferrer">View the selected repository <ArrowUpRight size={15} /></a>
  </main>;
}
